timestamp: '2025-02-02T13:26:42.812769'
joints:
  Shoulder_Rotation:
    max:
      ticks: 1307
      speed: 0
      load: 0
    center:
      ticks: 2641
      speed: 0
      load: 0
    min:
      ticks: 4046
      speed: 0
      load: 0
  Shoulder_Pitch:
    min:
      ticks: 3390
      speed: 0
      load: 0
    center:
      ticks: 647
      speed: 0
      load: 0
    max:
      ticks: 1744
      speed: 0
      load: 0
  Elbow:
    min:
      ticks: 2611
      speed: 0
      load: 0
    center:
      ticks: 3830
      speed: 0
      load: 0
    max:
      ticks: 681
      speed: 50
      load: 0
  Wrist_Pitch:
    min:
      ticks: 3322
      speed: 0
      load: 0
    center:
      ticks: 320
      speed: 0
      load: 0
    max:
      ticks: 681
      speed: 0
      load: 0
  Wrist_Roll:
    min:
      ticks: 394
      speed: 0
      load: 0
    center:
      ticks: 2369
      speed: 0
      load: 0
    max:
      ticks: 774
      speed: 0
      load: 0
  Gripper:
    min:
      ticks: 3689
      speed: 0
      load: 0
    center:
      ticks: 4043
      speed: 0
      load: 0
    max:
      ticks: 994
      speed: 0
      load: 0
